/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/carousel.vue')['default']
    CharacterCard: typeof import('./src/components/character-card.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    DropMenu: typeof import('./src/components/drop-menu.vue')['default']
    DzTravel: typeof import('./src/components/dz-travel.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Explain: typeof import('./src/components/explain.vue')['default']
    HorizontalSlider: typeof import('./src/components/horizontal-slider.vue')['default']
    Key: typeof import('./src/components/key.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveConfigBtn: typeof import('./src/components/save-config-btn.vue')['default']
    SetTravelCard: typeof import('./src/components/set-travel-card.vue')['default']
    TravelTestCard: typeof import('./src/components/travel-test-card.vue')['default']
  }
}
