
export default {
  0: {
    name: ' ',
    type: '特殊',
    comm: 'Empty key',
    hex16: '0x0000',
    typeof: 'special',
  },
  1: {
    name: '△',
    type: '特殊',
    comm: 'Transparent key',
    hex16: '0x0001',
    typeof: 'special',
  },
  4: {
    name: 'A',
    type: '基础',
    comm: '',
    hex16: '0x0004',
    typeof: 'basic',
  },
  5: {
    name: 'B',
    type: '基础',
    comm: '',
    hex16: '0x0005',
    typeof: 'basic',
  },
  6: {
    name: 'C',
    type: '基础',
    comm: '',
    hex16: '0x0006',
    typeof: 'basic',
  },
  7: {
    name: 'D',
    type: '基础',
    comm: '',
    hex16: '0x0007',
    typeof: 'basic',
  },
  8: {
    name: 'E',
    type: '基础',
    comm: '',
    hex16: '0x0008',
    typeof: 'basic',
  },
  9: {
    name: 'F',
    type: '基础',
    comm: '',
    hex16: '0x0009',
    typeof: 'basic',
  },
  10: {
    name: 'G',
    type: '基础',
    comm: '',
    hex16: '0x000A',
    typeof: 'basic',
  },
  11: {
    name: 'H',
    type: '基础',
    comm: '',
    hex16: '0x000B',
    typeof: 'basic',
  },
  12: {
    name: 'I',
    type: '基础',
    comm: '',
    hex16: '0x000C',
    typeof: 'basic',
  },
  13: {
    name: 'J',
    type: '基础',
    comm: '',
    hex16: '0x000D',
    typeof: 'basic',
  },
  14: {
    name: 'K',
    type: '基础',
    comm: '',
    hex16: '0x000E',
    typeof: 'basic',
  },
  15: {
    name: 'L',
    type: '基础',
    comm: '',
    hex16: '0x000F',
    typeof: 'basic',
  },
  16: {
    name: 'M',
    type: '基础',
    comm: '',
    hex16: '0x0010',
    typeof: 'basic',
  },
  17: {
    name: 'N',
    type: '基础',
    comm: '',
    hex16: '0x0011',
    typeof: 'basic',
  },
  18: {
    name: 'O',
    type: '基础',
    comm: '',
    hex16: '0x0012',
    typeof: 'basic',
  },
  19: {
    name: 'P',
    type: '基础',
    comm: '',
    hex16: '0x0013',
    typeof: 'basic',
  },
  20: {
    name: 'Q',
    type: '基础',
    comm: '',
    hex16: '0x0014',
    typeof: 'basic',
  },
  21: {
    name: 'R',
    type: '基础',
    comm: '',
    hex16: '0x0015',
    typeof: 'basic',
  },
  22: {
    name: 'S',
    type: '基础',
    comm: '',
    hex16: '0x0016',
    typeof: 'basic',
  },
  23: {
    name: 'T',
    type: '基础',
    comm: '',
    hex16: '0x0017',
    typeof: 'basic',
  },
  24: {
    name: 'U',
    type: '基础',
    comm: '',
    hex16: '0x0018',
    typeof: 'basic',
  },
  25: {
    name: 'V',
    type: '基础',
    comm: '',
    hex16: '0x0019',
    typeof: 'basic',
  },
  26: {
    name: 'W',
    type: '基础',
    comm: '',
    hex16: '0x001A',
    typeof: 'basic',
  },
  27: {
    name: 'X',
    type: '基础',
    comm: '',
    hex16: '0x001B',
    typeof: 'basic',
  },
  28: {
    name: 'Y',
    type: '基础',
    comm: '',
    hex16: '0x001C',
    typeof: 'basic',
  },
  29: {
    name: 'Z',
    type: '基础',
    comm: '',
    hex16: '0x001D',
    typeof: 'basic',
  },
  30: {
    name: '1 !',
    type: '基础',
    comm: '',
    hex16: '0x001E',
    typeof: 'basic',
  },
  31: {
    name: '2 @',
    type: '基础',
    comm: '',
    hex16: '0x001F',
    typeof: 'basic',
  },
  32: {
    name: '3 #',
    type: '基础',
    comm: '',
    hex16: '0x0020',
    typeof: 'basic',
  },
  33: {
    name: '4 $',
    type: '基础',
    comm: '',
    hex16: '0x0021',
    typeof: 'basic',
  },
  34: {
    name: '5 %',
    type: '基础',
    comm: '',
    hex16: '0x0022',
    typeof: 'basic',
  },
  35: {
    name: '6 ^',
    type: '基础',
    comm: '',
    hex16: '0x0023',
    typeof: 'basic',
  },
  36: {
    name: '7 &',
    type: '基础',
    comm: '',
    hex16: '0x0024',
    typeof: 'basic',
  },
  37: {
    name: '8 *',
    type: '基础',
    comm: '',
    hex16: '0x0025',
    typeof: 'basic',
  },
  38: {
    name: '9 (',
    type: '基础',
    comm: '',
    hex16: '0x0026',
    typeof: 'basic',
  },
  39: {
    name: '0 )',
    type: '基础',
    comm: '',
    hex16: '0x0027',
    typeof: 'basic',
  },
  40: {
    name: 'Enter',
    type: '基础',
    comm: '',
    hex16: '0x0028',
    typeof: 'basic',
  },
  41: {
    name: 'Esc',
    type: '基础',
    comm: '',
    hex16: '0x0029',
    typeof: 'basic',
  },
  42: {
    name: 'Backspace',
    type: '基础',
    comm: '',
    hex16: '0x002A',
    typeof: 'basic',
  },
  43: {
    name: 'Tab',
    type: '基础',
    comm: '',
    hex16: '0x002B',
    typeof: 'basic',
  },
  44: {
    name: 'Space',
    type: '基础',
    comm: '',
    hex16: '0x002C',
    typeof: 'basic',
  },
  45: {
    name: '- _',
    type: '基础',
    comm: '',
    hex16: '0x002D',
    typeof: 'basic',
  },
  46: {
    name: '= +',
    type: '基础',
    comm: '',
    hex16: '0x002E',
    typeof: 'basic',
  },
  47: {
    name: '[ {',
    type: '基础',
    comm: '',
    hex16: '0x002F',
    typeof: 'basic',
  },
  48: {
    name: '] }',
    type: '基础',
    comm: '',
    hex16: '0x0030',
    typeof: 'basic',
  },
  49: {
    name: '\\ |',
    type: '基础',
    comm: '',
    hex16: '0x0031',
    typeof: 'basic',
  },
  50: {
    name: '# ~',
    type: '基础',
    comm: '',
    hex16: '0x0032',
    typeof: 'basic',
  },
  51: {
    name: '; :',
    type: '基础',
    comm: '',
    hex16: '0x0033',
    typeof: 'basic',
  },
  52: {
    name: '\' "',
    type: '基础',
    comm: '',
    hex16: '0x0034',
    typeof: 'basic',
  },
  53: {
    name: '` ~',
    type: '基础',
    comm: '',
    hex16: '0x0035',
    typeof: 'basic',
  },
  54: {
    name: ', <',
    type: '基础',
    comm: '',
    hex16: '0x0036',
    typeof: 'basic',
  },
  55: {
    name: '. >',
    type: '基础',
    comm: '',
    hex16: '0x0037',
    typeof: 'basic',
  },
  56: {
    name: '/ ?',
    type: '基础',
    comm: '',
    hex16: '0x0038',
    typeof: 'basic',
  },
  57: {
    name: 'Caps',
    type: '基础',
    comm: '',
    hex16: '0x0039',
    typeof: 'basic',
  },
  58: {
    name: 'F1',
    type: '基础',
    comm: '',
    hex16: '0x003A',
    typeof: 'basic',
  },
  59: {
    name: 'F2',
    type: '基础',
    comm: '',
    hex16: '0x003B',
    typeof: 'basic',
  },
  60: {
    name: 'F3',
    type: '基础',
    comm: '',
    hex16: '0x003C',
    typeof: 'basic',
  },
  61: {
    name: 'F4',
    type: '基础',
    comm: '',
    hex16: '0x003D',
    typeof: 'basic',
  },
  62: {
    name: 'F5',
    type: '基础',
    comm: '',
    hex16: '0x003E',
    typeof: 'basic',
  },
  63: {
    name: 'F6',
    type: '基础',
    comm: '',
    hex16: '0x003F',
    typeof: 'basic',
  },
  64: {
    name: 'F7',
    type: '基础',
    comm: '',
    hex16: '0x0040',
    typeof: 'basic',
  },
  65: {
    name: 'F8',
    type: '基础',
    comm: '',
    hex16: '0x0041',
    typeof: 'basic',
  },
  66: {
    name: 'F9',
    type: '基础',
    comm: '',
    hex16: '0x0042',
    typeof: 'basic',
  },
  67: {
    name: 'F10',
    type: '基础',
    comm: '',
    hex16: '0x0043',
    typeof: 'basic',
  },
  68: {
    name: 'F11',
    type: '基础',
    comm: '',
    hex16: '0x0044',
    typeof: 'basic',
  },
  69: {
    name: 'F12',
    type: '基础',
    comm: '',
    hex16: '0x0045',
    typeof: 'basic',
  },
  70: {
    name: 'PrtScr',
    type: '基础',
    comm: '',
    hex16: '0x0046',
    typeof: 'basic',
  },
  71: {
    name: 'Scroll',
    type: '基础',
    comm: '',
    hex16: '0x0047',
    typeof: 'basic',
  },
  72: {
    name: 'Pause',
    type: '基础',
    comm: '',
    hex16: '0x0048',
    typeof: 'basic',
  },
  73: {
    name: 'Insert',
    type: '基础',
    comm: '',
    hex16: '0x0049',
    typeof: 'basic',
  },
  74: {
    name: 'Home',
    type: '基础',
    comm: '',
    hex16: '0x004A',
    typeof: 'basic',
  },
  75: {
    name: 'PgUp',
    type: '基础',
    comm: '',
    hex16: '0x004B',
    typeof: 'basic',
  },
  76: {
    name: 'Delete',
    type: '基础',
    comm: '',
    hex16: '0x004C',
    typeof: 'basic',
  },
  77: {
    name: 'End',
    type: '基础',
    comm: '',
    hex16: '0x004D',
    typeof: 'basic',
  },
  78: {
    name: 'PgDn',
    type: '基础',
    comm: '',
    hex16: '0x004E',
    typeof: 'basic',
  },
  79: {
    name: '→',
    type: '基础',
    comm: '',
    hex16: '0x004F',
    typeof: 'basic',
  },
  80: {
    name: '←',
    type: '基础',
    comm: '',
    hex16: '0x0050',
    typeof: 'basic',
  },
  81: {
    name: '↓',
    type: '基础',
    comm: '',
    hex16: '0x0051',
    typeof: 'basic',
  },
  82: {
    name: '↑',
    type: '基础',
    comm: '',
    hex16: '0x0052',
    typeof: 'basic',
  },
  83: {
    name: 'Num Lock',
    type: '基础',
    comm: '',
    hex16: '0x0053',
    typeof: 'basic',
  },
  84: {
    name: "/',",
    type: '基础',
    comm: '',
    hex16: '0x0054',
    typeof: 'basic',
  },
  85: {
    name: "*',",
    type: '基础',
    comm: '',
    hex16: '0x0055',
    typeof: 'basic',
  },
  86: {
    name: "-',",
    type: '基础',
    comm: '',
    hex16: '0x0056',
    typeof: 'basic',
  },
  87: {
    name: "+',",
    type: '基础',
    comm: '',
    hex16: '0x0057',
    typeof: 'basic',
  },
  88: {
    name: 'PEnter',
    type: '基础',
    comm: '',
    hex16: '0x0058',
    typeof: 'basic',
  },
  89: {
    name: 'P1',
    type: '基础',
    comm: '',
    hex16: '0x0059',
    typeof: 'basic',
  },
  90: {
    name: 'P2',
    type: '基础',
    comm: '',
    hex16: '0x005A',
    typeof: 'basic',
  },
  91: {
    name: 'P3',
    type: '基础',
    comm: '',
    hex16: '0x005B',
    typeof: 'basic',
  },
  92: {
    name: 'P4',
    type: '基础',
    comm: '',
    hex16: '0x005C',
    typeof: 'basic',
  },
  93: {
    name: 'P5',
    type: '基础',
    comm: '',
    hex16: '0x005D',
    typeof: 'basic',
  },
  94: {
    name: 'P6',
    type: '基础',
    comm: '',
    hex16: '0x005E',
    typeof: 'basic',
  },
  95: {
    name: 'P7',
    type: '基础',
    comm: '',
    hex16: '0x005F',
    typeof: 'basic',
  },
  96: {
    name: 'P8',
    type: '基础',
    comm: '',
    hex16: '0x0060',
    typeof: 'basic',
  },
  97: {
    name: 'P9',
    type: '基础',
    comm: '',
    hex16: '0x0061',
    typeof: 'basic',
  },
  98: {
    name: 'P0',
    type: '基础',
    comm: '',
    hex16: '0x0062',
    typeof: 'basic',
  },
  99: {
    name: '. Del',
    type: '基础',
    comm: '',
    hex16: '0x0063',
    typeof: 'basic',
  },
  100: {
    name: 'Nubs',
    type: '基础',
    comm: '',
    hex16: '0x0064',
    typeof: 'basic',
  },
  101: {
    name: 'App',
    type: '基础',
    comm: '',
    hex16: '0x0065',
    typeof: 'basic',
  },
  102: {
    name: 'Power',
    type: '基础',
    comm: '',
    hex16: '0x0066',
    typeof: 'basic',
  },
  103: {
    name: 'Peql',
    type: '基础',
    comm: '',
    hex16: '0x0067',
    typeof: 'basic',
  },
  104: {
    name: 'F13',
    type: '基础',
    comm: '',
    hex16: '0x0068',
    typeof: 'basic',
  },
  105: {
    name: 'F14',
    type: '基础',
    comm: '',
    hex16: '0x0069',
    typeof: 'basic',
  },
  106: {
    name: 'F15',
    type: '基础',
    comm: '',
    hex16: '0x006A',
    typeof: 'basic',
  },
  107: {
    name: 'F16',
    type: '基础',
    comm: '',
    hex16: '0x006B',
    typeof: 'basic',
  },
  108: {
    name: 'F17',
    type: '基础',
    comm: '',
    hex16: '0x006C',
    typeof: 'basic',
  },
  109: {
    name: 'F18',
    type: '基础',
    comm: '',
    hex16: '0x006D',
    typeof: 'basic',
  },
  110: {
    name: 'F19',
    type: '基础',
    comm: '',
    hex16: '0x006E',
    typeof: 'basic',
  },
  111: {
    name: 'F20',
    type: '基础',
    comm: '',
    hex16: '0x006F',
    typeof: 'basic',
  },
  112: {
    name: 'F21',
    type: '基础',
    comm: '',
    hex16: '0x0070',
    typeof: 'basic',
  },
  113: {
    name: 'F22',
    type: '基础',
    comm: '',
    hex16: '0x0071',
    typeof: 'basic',
  },
  114: {
    name: 'F23',
    type: '基础',
    comm: '',
    hex16: '0x0072',
    typeof: 'basic',
  },
  115: {
    name: 'F24',
    type: '基础',
    comm: '',
    hex16: '0x0073',
    typeof: 'basic',
  },
  224: {
    name: 'L-Ctrl',
    type: '基础',
    comm: '',
    hex16: '0x00E0',
    typeof: 'basic',
  },
  225: {
    name: 'L-Shift',
    type: '基础',
    comm: '',
    hex16: '0x00E1',
    typeof: 'basic',
  },
  226: {
    name: 'L-Alt',
    type: '基础',
    comm: '',
    hex16: '0x00E2',
    typeof: 'basic',
  },
  227: {
    name: 'L-Gui',
    type: '基础',
    comm: '',
    hex16: '0x00E3',
    typeof: 'basic',
  },
  228: {
    name: 'R-Ctrl',
    type: '基础',
    comm: '',
    hex16: '0x00E4',
    typeof: 'basic',
  },
  229: {
    name: 'R-Shift',
    type: '基础',
    comm: '',
    hex16: '0x00E5',
    typeof: 'basic',
  },
  230: {
    name: 'R-Alt',
    type: '基础',
    comm: '',
    hex16: '0x00E6',
    typeof: 'basic',
  },
  231: {
    name: 'R-Gui',
    type: '基础',
    comm: '',
    hex16: '0x00E7',
    typeof: 'basic',
  },
  4434: {
    name: 'MCON',
    type: '系统',
    comm: 'MacOS Console',
    hex16: '0x1152',
    typeof: 'system',
  },
  4905: {
    name: 'WTMG',
    type: '系统',
    comm: 'Windows Task Manager',
    hex16: '0x1329',
    typeof: 'system',
  },
  6151: {
    name: 'WDSK',
    type: '系统',
    comm: 'Windows Desktop',
    hex16: '0x1807',
    typeof: 'system',
  },
  6152: {
    name: 'WFIL',
    type: '系统',
    comm: 'Windows File Explorer',
    hex16: '0x1808',
    typeof: 'system',
  },
  6165: {
    name: 'WCMD',
    type: '系统',
    comm: 'Windows Run',
    hex16: '0x1815',
    typeof: 'system',
  },
  8303: {
    name: 'Bri+',
    type: '多媒体',
    comm: 'Brightness +',
    hex16: '0x206F',
    typeof: 'media',
  },
  8304: {
    name: 'Bri-',
    type: '多媒体',
    comm: 'Brightness -',
    hex16: '0x2070',
    typeof: 'media',
  },
  8373: {
    name: 'Next',
    type: '多媒体',
    comm: 'Next Track',
    hex16: '0x20B5',
    typeof: 'media',
  },
  8374: {
    name: 'Prev',
    type: '多媒体',
    comm: 'Previous Track',
    hex16: '0x20B6',
    typeof: 'media',
  },
  8375: {
    name: 'Stop',
    type: '多媒体',
    comm: 'Stop Playback',
    hex16: '0x20B7',
    typeof: 'media',
  },
  8397: {
    name: 'Play',
    type: '多媒体',
    comm: 'Play/Pause',
    hex16: '0x20CD',
    typeof: 'media',
  },
  8418: {
    name: 'Mute',
    type: '多媒体',
    comm: 'Mute',
    hex16: '0x20E2',
    typeof: 'media',
  },
  8425: {
    name: 'Vol+',
    type: '多媒体',
    comm: 'Volume +',
    hex16: '0x20E9',
    typeof: 'media',
  },
  8426: {
    name: 'Vol-',
    type: '多媒体',
    comm: 'Volume -',
    hex16: '0x20EA',
    typeof: 'media',
  },
  8579: {
    name: 'Music',
    type: '多媒体',
    comm: 'Music',
    hex16: '0x2183',
    typeof: 'media',
  },
  8586: {
    name: 'Vol-',
    type: '多媒体',
    comm: 'Mail',
    hex16: '0x218A',
    typeof: 'media',
  },
  8594: {
    name: 'Calc',
    type: '多媒体',
    comm: 'Calculator',
    hex16: '0x2192',
    typeof: 'media',
  },
  8596: {
    name: 'Mute',
    type: '多媒体',
    comm: 'My Computer',
    hex16: '0x2194',
    typeof: 'media',
  },
  8739: {
    name: 'Vol+',
    type: '多媒体',
    comm: 'Browser',
    hex16: '0x2223',
    typeof: 'media',
  },
  16384: {
    name: 'M-Free',
    type: '鼠标',
    comm: 'Mouse Release',
    hex16: '0x4000',
    typeof: 'mouse',
  },
  16640: {
    name: 'M-Left',
    type: '鼠标',
    comm: 'Mouse Left Button',
    hex16: '0x4100',
    typeof: 'mouse',
  },
  16896: {
    name: 'M-Right',
    type: '鼠标',
    comm: 'Mouse Right Button',
    hex16: '0x4200',
    typeof: 'mouse',
  },
  17152: {
    name: 'M-Middle',
    type: '鼠标',
    comm: 'Mouse Middle Button',
    hex16: '0x4300',
    typeof: 'mouse',
  },
  17408: {
    name: 'M-Forward',
    type: '鼠标',
    comm: 'Mouse Wheel Forward',
    hex16: '0x4400',
    typeof: 'mouse',
  },
  17664: {
    name: 'M-Back',
    type: '鼠标',
    comm: 'Mouse Wheel Backward',
    hex16: '0x4500',
    typeof: 'mouse',
  },
  19978: {
    name: 'M-ZHR',
    type: '鼠标',
    comm: 'Mouse Move Right',
    hex16: '0x4E0A',
    typeof: 'mouse',
  },
  20214: {
    name: 'M-ZHL',
    type: '鼠标',
    comm: 'Mouse Move Left',
    hex16: '0x4EF6',
    typeof: 'mouse',
  },
  20234: {
    name: 'M-ZVR',
    type: '鼠标',
    comm: 'Mouse Move Up',
    hex16: '0x4F0A',
    typeof: 'mouse',
  },
  20470: {
    name: 'M-ZVL',
    type: '鼠标',
    comm: 'Mouse Move Down',
    hex16: '0x4FF6',
    typeof: 'mouse',
  },
  61696: {
    name: 'Fn0',
    type: '特殊',
    comm: 'Switch to Main Layer',
    hex16: '0xF100',
    typeof: 'special',
  },
  61697: {
    name: 'Fn1',
    type: '特殊',
    comm: 'Switch to Fn1 Layer',
    hex16: '0xF101',
    typeof: 'special',
  },
  61698: {
    name: 'Fn2',
    type: '特殊',
    comm: 'Switch to Fn2 Layer',
    hex16: '0xF102',
    typeof: 'special',
  },
  61699: {
    name: 'Fn3',
    type: '特殊',
    comm: 'Switch to Fn3 Layer',
    hex16: '0xF103',
    typeof: 'special',
  },
  61952: {
    name: 'Reset',
    type: '控制',
    comm: 'Restore factory settings (long press to activate)',
    hex16: '0xF200',
    typeof: 'control',
  },
  61953: {
    name: 'Win',
    type: '控制',
    comm: 'Switch to Windows layout (long press to activate)',
    hex16: '0xF201',
    typeof: 'control',
  },
  61954: {
    name: 'Mac',
    type: '控制',
    comm: 'Switch to Mac layout (long press to activate)',
    hex16: '0xF202',
    typeof: 'control',
  },
  61955: {
    name: 'Adj',
    type: '控制',
    comm: 'Calibrate magnetic axis (long press to activate)',
    hex16: '0xF203',
    typeof: 'control',
  },
  61957: {
    name: 'Config1',
    type: '控制',
    comm: 'Switch to Config 1',
    hex16: '0xF205',
    typeof: 'control',
  },
  61958: {
    name: 'Config2',
    type: '控制',
    comm: 'Switch to Config 2',
    hex16: '0xF206',
    typeof: 'control',
  },
  61959: {
    name: 'Config3',
    type: '控制',
    comm: 'Switch to Config 3',
    hex16: '0xF207',
    typeof: 'control',
  },
  61960: {
    name: 'Config4',
    type: '控制',
    comm: 'Switch to Config 4',
    hex16: '0xF208',
    typeof: 'control',
  },
  61961: {
    name: 'LockWin',
    type: '控制',
    comm: 'Lock Win key',
    hex16: '0xF209',
    typeof: 'control',
  },
  62208: {
    name: 'Mode',
    type: '灯光',
    comm: 'Lighting mode switch',
    hex16: '0xF300',
    typeof: 'light',
  },
  62209: {
    name: 'Color',
    type: '灯光',
    comm: 'Lighting color switch',
    hex16: '0xF301',
    typeof: 'light',
  },
  62210: {
    name: 'Bri+',
    type: '灯光',
    comm: 'Lighting brightness +',
    hex16: '0xF302',
    typeof: 'light',
  },
  62211: {
    name: 'Bri-',
    type: '灯光',
    comm: 'Lighting brightness -',
    hex16: '0xF303',
    typeof: 'light',
  },
  62212: {
    name: 'Spd+',
    type: '灯光',
    comm: 'Lighting speed +',
    hex16: '0xF304',
    typeof: 'light',
  },
  62213: {
    name: 'Spd-',
    type: '灯光',
    comm: 'Lighting speed -',
    hex16: '0xF305',
    typeof: 'light',
  },
  62214: {
    name: 'Prev',
    type: '灯光',
    comm: 'Lighting previous mode',
    hex16: '0xF306',
    typeof: 'light',
  },
  62215: {
    name: 'OnOff',
    type: '灯光',
    comm: 'Toggle lighting',
    hex16: '0xF307',
    typeof: 'light',
  },
  62216: {
    name: 'Dir',
    type: '灯光',
    comm: 'Lighting direction',
    hex16: '0xF308',
    typeof: 'light',
  },
  62224: {
    name: 'D1_Mode',
    type: '灯光',
    comm: 'Decorative light - mode switch',
    hex16: '0xF310',
    typeof: 'light',
  },
  62225: {
    name: 'D1_Color',
    type: '灯光',
    comm: 'Decorative light - color switch',
    hex16: '0xF311',
    typeof: 'light',
  },
  62226: {
    name: 'D1_Bri+',
    type: '灯光',
    comm: 'Decorative light - brightness +',
    hex16: '0xF312',
    typeof: 'light',
  },
  62227: {
    name: 'D1_Bri-',
    type: '灯光',
    comm: 'Decorative light - brightness -',
    hex16: '0xF313',
    typeof: 'light',
  },
  62228: {
    name: 'D1_Spd+',
    type: '灯光',
    comm: 'Decorative light - speed +',
    hex16: '0xF314',
    typeof: 'light',
  },
  62229: {
    name: 'D1_Spd-',
    type: '灯光',
    comm: 'Decorative light - speed -',
    hex16: '0xF315',
    typeof: 'light',
  },
  62230: {
    name: 'D1_Prev',
    type: '灯光',
    comm: 'Decorative light - previous mode',
    hex16: '0xF316',
    typeof: 'light',
  },
  62231: {
    name: 'D1_OnOff',
    type: '灯光',
    comm: 'Decorative light - toggle',
    hex16: '0xF317',
    typeof: 'light',
  },
  62232: {
    name: 'D1_Dir',
    type: '灯光',
    comm: 'Decorative light - direction',
    hex16: '0xF318',
    typeof: 'light',
  },
  62240: {
    name: 'D2_Mode',
    type: '灯光',
    comm: 'Decorative light 2 - mode switch',
    hex16: '0xF320',
    typeof: 'light',
  },
  62241: {
    name: 'D2_Color',
    type: '灯光',
    comm: 'Decorative light 2 - color switch',
    hex16: '0xF321',
    typeof: 'light',
  },
  62242: {
    name: 'D2_Bri+',
    type: '灯光',
    comm: 'Decorative light 2 - brightness +',
    hex16: '0xF322',
    typeof: 'light',
  },
  62243: {
    name: 'D2_Bri-',
    type: '灯光',
    comm: 'Decorative light 2 - brightness -',
    hex16: '0xF323',
    typeof: 'light',
  },
  62244: {
    name: 'D2_Spd+',
    type: '灯光',
    comm: 'Decorative light 2 - speed +',
    hex16: '0xF324',
    typeof: 'light',
  },
  62245: {
    name: 'D2_Spd-',
    type: '灯光',
    comm: 'Decorative light 2 - speed -',
    hex16: '0xF325',
    typeof: 'light',
  },
  62246: {
    name: 'D2_Prev',
    type: '灯光',
    comm: 'Decorative light 2 - previous mode',
    hex16: '0xF326',
    typeof: 'light',
  },
  62247: {
    name: 'D2_OnOff',
    type: '灯光',
    comm: 'Decorative light 2 - toggle',
    hex16: '0xF327',
    typeof: 'light',
  },
  62248: {
    name: 'D2_Dir',
    type: '灯光',
    comm: 'Decorative light 2 - direction',
    hex16: '0xF328',
    typeof: 'light',
  },
  62256: {
    name: 'D3_Mode',
    type: '灯光',
    comm: 'Decorative light 3 - mode switch',
    hex16: '0xF330',
    typeof: 'light',
  },
  62257: {
    name: 'D3_Color',
    type: '灯光',
    comm: 'Decorative light 3 - color switch',
    hex16: '0xF331',
    typeof: 'light',
  },
  62258: {
    name: 'D3_Bri+',
    type: '灯光',
    comm: 'Decorative light 3 - brightness +',
    hex16: '0xF332',
    typeof: 'light',
  },
  62259: {
    name: 'D3_Bri-',
    type: '灯光',
    comm: 'Decorative light 3 - brightness -',
    hex16: '0xF333',
    typeof: 'light',
  },
  62260: {
    name: 'D3_Spd+',
    type: '灯光',
    comm: 'Decorative light 3 - speed +',
    hex16: '0xF334',
    typeof: 'light',
  },
  62261: {
    name: 'D3_Spd-',
    type: '灯光',
    comm: 'Decorative light 3 - speed -',
    hex16: '0xF335',
    typeof: 'light',
  },
  62262: {
    name: 'D3_Prev',
    type: '灯光',
    comm: 'Decorative light 3 - previous mode',
    hex16: '0xF336',
    typeof: 'light',
  },
  62263: {
    name: 'D3_OnOff',
    type: '灯光',
    comm: 'Decorative light 3 - toggle',
    hex16: '0xF337',
    typeof: 'light',
  },
  62264: {
    name: 'D3_Dir',
    type: '灯光',
    comm: 'Decorative light 3 - direction',
    hex16: '0xF338',
    typeof: 'light',
  },
  62464: {
    name: 'USB',
    type: '三模',
    comm: 'Switch to USB mode',
    hex16: '0xF400',
    typeof: 'triMode',
  },
  62465: {
    name: '24G',
    type: '三模',
    comm: 'Switch to 2.4G mode (short press to switch, long press to pair)',
    hex16: '0xF401',
    typeof: 'triMode',
  },
  62466: {
    name: 'BLE1',
    type: '三模',
    comm: 'Switch to Bluetooth 1 mode (short press to switch, long press to pair)',
    hex16: '0xF402',
    typeof: 'triMode',
  },
  62467: {
    name: 'BLE2',
    type: '三模',
    comm: 'Switch to Bluetooth 2 mode (short press to switch, long press to pair)',
    hex16: '0xF403',
    typeof: 'triMode',
  },
  62468: {
    name: 'BLE3',
    type: '三模',
    comm: 'Switch to Bluetooth 3 mode (short press to switch, long press to pair)',
    hex16: '0xF404',
    typeof: 'triMode',
  },
  62469: {
    name: 'Reset',
    type: '三模',
    comm: 'Clear pairing data',
    hex16: '0xF405',
    typeof: 'triMode',
  },
  62470: {
    name: 'Batt',
    type: '三模',
    comm: 'Query battery',
    hex16: '0xF406',
    typeof: 'triMode',
  },
  62720: {
    name: 'M0',
    type: '宏',
    comm: '',
    hex16: '0xF500',
    typeof: 'macro',
  },
  62721: {
    name: 'M1',
    type: '宏',
    comm: '',
    hex16: '0xF501',
    typeof: 'macro',
  },
  62722: {
    name: 'M2',
    type: '宏',
    comm: '',
    hex16: '0xF502',
    typeof: 'macro',
  },
  62723: {
    name: 'M3',
    type: '宏',
    comm: '',
    hex16: '0xF503',
    typeof: 'macro',
  },
  62724: {
    name: 'M4',
    type: '宏',
    comm: '',
    hex16: '0xF504',
    typeof: 'macro',
  },
  62725: {
    name: 'M5',
    type: '宏',
    comm: '',
    hex16: '0xF505',
    typeof: 'macro',
  },
  62726: {
    name: 'M6',
    type: '宏',
    comm: '',
    hex16: '0xF506',
    typeof: 'macro',
  },
  62727: {
    name: 'M7',
    type: '宏',
    comm: '',
    hex16: '0xF507',
    typeof: 'macro',
  },
  62728: {
    name: 'M8',
    type: '宏',
    comm: '',
    hex16: '0xF508',
    typeof: 'macro',
  },
  62729: {
    name: 'M9',
    type: '宏',
    comm: '',
    hex16: '0xF509',
    typeof: 'macro',
  },
  62730: {
    name: 'M10',
    type: '宏',
    comm: '',
    hex16: '0xF50A',
    typeof: 'macro',
  },
  62731: {
    name: 'M11',
    type: '宏',
    comm: '',
    hex16: '0xF50B',
    typeof: 'macro',
  },
  62732: {
    name: 'M12',
    type: '宏',
    comm: '',
    hex16: '0xF50C',
    typeof: 'macro',
  },
  62733: {
    name: 'M13',
    type: '宏',
    comm: '',
    hex16: '0xF50D',
    typeof: 'macro',
  },
  62734: {
    name: 'M14',
    type: '宏',
    comm: '',
    hex16: '0xF50E',
    typeof: 'macro',
  },
  62735: {
    name: 'M15',
    type: '宏',
    comm: '',
    hex16: '0xF50F',
    typeof: 'macro',
  },
};
